name: Reusable workflow test-frontend

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
    secrets:
      kubeconfig:
        required: true
        type: string
        
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
        id: install
      - name: Set kube context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.CS_TEST_K8S_CONFIG }}
      - name: Deploy to kubernetes
        run: |
          ${{ steps.install.outputs.kubectl-path}} get po -n $DEPLOY_NAME_SPACE
