name: Reusable workflow test-frontend

on:
  workflow_call:
    
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Deploy to kubernetes
        run: |
          echo "kubectl get po -n $DEPLOY_NAME_SPACE"
